### ISSUE TITLE
Which Motion Controller?

### ISSUE THREAD

**Issue by davner** [so-90prime/90prime#1]
# Which Motion Controller?
We are in the middle of deciding between which motion controller to use. Below is some initial thoughts from various people. 

## How To Use This Issue
Use this space to keep information in one spot. This is to solve the various email chains we have discussing pros and cons of various motion controllers. 

## Motion Control Axes
We need **7** control axes:
- Focus actuator A
- Focus actuator B
- Focus actuator C
- Filter wheel rotation
- Filter wheel translation arm
- Guider focus
- Guider filter wheel

### Galil
**Dan A.**
> - Familiarity with the controller
> - Rock solid - has been working for 20 years without issue
> - Galilcode can be "dropped in" without heavy modification (after CJ, Greg and I verify the code does not contain bugs/issues)
> - Network upgrades - Galil can now have 8 simultaneous connections as well as be programmed to reject all traffic coming in from port 1000 and below
> - Galil maintained "galilserver" - Galil engineers wrote their own galilserver. This would replace galil server and could fix galil lockup. 
> - Time is saved not having to learn new controller and develop lowlevel controller code. 
> 
> Cons:
> - Network issues - for some odd reason Galil will not incorporate some command to listen only on one or a couple ports. It is open for everything on the network to communicate with. This leaves us having the same problems that we are currently facing. Instead of simplifying the system overview, we are maintaining the same complexity.
> - Software Inheritance - the galilcode previously written could be the culprit for the galil lockups. It could be more of a curse than a blessing reusing that code and having to debug it. 
> 
> Neutral:
> - Software design changes - Using galil could change the overall design. Instead of an INDI driver, server, client it would be galilcode, galilserver type thing, GUIs. 

**Chris J.**
> PROS
> 1)  the previous unit worked for 20 years without ever installing the spare.  long life is typical with this company
> 2)  we can install the old code on the new version without any serious modification
> 3)  I think the form factor is the same..  so its a drop in replacement(not sure about this, though)
> 4)  They have improved networking some.
> 
> CONS
> 1)  as much as they improved networking, its still not great and is going to require us to add additional hardware to make it workable...  The sales rep admitted that they do not intend for this to be on a network.  They prefer it to be hooked directly to a computer...  thats not really how things at the 90" work.
> 
> We can make a new galil unit work..  I have ideas..  but they all come at a cost(additional hardware, increased complexity...  thus more failure modes).  I REALLY think we should explore other options before we settle on this.  Theres a good chance that there's something out there that is a better fit.

### Delta Tau
**Tim P.**
> The MMTO is heavily invested in delta tau controllers largely because it’s what the instrument builders at SAO have spec’ed. So hecto, binospec, the f/5 wfs stages, and the f/5 hexapod are all run by delta tau PMAC or UMAC controllers. The f/5 hexapod started off with some pseudo-homegrown PIC-based motor control system, but that failed pretty miserably so we ultimately paid up and did it right with delta tau. These control systems have been in operation since the early 2000’s and they have a solid track record of reliability.
> 
> At SALT they were much more invested in PI (https://www.pi-usa.us/) for a lot of the critical control systems. IIRC, our f/9 hexapod is also a PI system, vintage 1998 or 1999.
> 
> Both delta tau and PI controllers can allow you to build coordinate transformations directly into the controller if you need to implement coordinated motion between the axes. We do this with our hexapods so that the transform matrices get loaded into the controllers so you can just command, say, a platform tilt of 10” along some axis and it’ll do it. We also do it with the f/5 wfs/mmtcam system where the pickoff mirror changes angle to match the changing beam angle as you move out in the field of view. Not sure if galil provides anything like that. If your 7 axes include instrument/optics positioning, that seems like it would be a relevant feature.

**Behzad A.** (PND writes: Behzad Abareshi and I worked on the WTTM @ NOAO where we used the Delta Tau controllers.)

> Depending on the level of precision and synchronization in your requirements, you may break the seven axes into a couple of groups with fewer axes, which opens up lots of options, like motors that have built-in servos (like Hydra's SmartMotors). For multiple-axis motion control Delta Tau boards have a reputation (you may recall that WTTM's XY stage was controlled by a Delta Tau).

**Shelby Gott** (Shelby is an old-school programmer based, pretty much, at KPNO.  His office was a cave of wonders with PDP-11s and all sorts that he used to keep running! I asked him about DESI etc). 

The DESI hexapod is from A.D.S. International.

I heard that Hydra is being re-designed by "PROD" with new actuators.
Don't know what kind, or who "PROD" is, but maybe Eric has some info on that?

### Moog Animatics SmartMotors
**Scott S.**

> For the VATT guidebox we used these Moog Animatics SmartMotors. I wrote most of the software (with a lot of help from CJ) and I really liked them. I thought the programming was straightforward and simple. It is a bit of a different topology than Delta Tau or Galil in that there is no central motion control card. The smarts for the motors are built in. At VATT, I had one primary motor that was connected to a PC via RS-485 and you could control all the other motors via this one connection.Their Combitronic communication system made this really easy!

**Comment by alexrgibbs** [comment]
How about adding absolute linear encoders where the LVDTs are, and hook the encoders directly to the motion controllers so they can independently take care of getting the actuators to the commanded positions.  This should be faster and more reliable than using the LVDTs, if the LVDTs are independently read like I think they are (?).  A bonus is that you could tell the motion controllers to actively hold the positions, if desired.  One possible issue is the environment, but since they don't need to move far they would probably stay pretty clean.  You'd want magnetic ones instead of optical for this reason, and due to the obvious issue of stray light.  I don't know how precise the positioning needs to be either, but I believe magnetic encoders can get to 1-10 um.

**Comment by davner** [comment]
@alexrgibbs I created a new issue from your comment. Let's continue the conversation about LVDTs there.

**Comment by grstafford** [comment]
**Greg - Thoughts on Galil Motion Controller**
**PROS:**
1. Familiarity with the controller
2. Used extensively on 90Prime & Mont4K instruments for the last 18 & 16 or so years, respectively.
3. Existing "Galil code"  portable to newer generation Galil motion controllers requiring less development.
4. When properly installed and properly communicated to per manufacturing recommendations/specifications and industry standards, Galil Motion controllers operates flawlessly.
5. Galil Motion has developed a Galilserver like solution for controlling network traffic, GCAPS, that resides on a small single board computer, like we use on our TCS and ITL uses on their camera controller, which enables Galil Motion Controllers to be placed on a non-isolated network. We currently have a hardware Firewall in between our Galil Motion Controller and our network to combat any issues regarding this matter.

**CONS:**
1. There has been talk about the Galil locking up at times, but this hasn't been verified nor has it been determined the cause since installing the hardware firewall. This seems to be a carry over from the time we had network traffic issues with the Galil, where the Galil did not respond well to multiple attempts at connecting/pinged from various computers on a network.  This problem was initially mitigated by the use of our GalilServer, which regulates traffic between ASCAM and Filter Wheel GUI (perhaps others) and the Galil Motion Controller.  When it was observed that laptops with certain anti-virus software would ping other devices on a network causing some Galil hiccups, a hardware firewall was installed.

2. A major problem with interpreting 90Prime operation problems accurately has been every time a problem arises it's reported as a "Galil lockup." I can explain all the hardware failures we have seen throughout the years and also how the system could get confused depending on what is going on at the time. Above the Galil, there is the Hardware Firewall - Network - GalilServer - ASCAM/FilterWheelGUI/Other Computers. Getting all devises synced back up together is sometimes problematic. One thing is for sure, Melanie Waidanz documented FilterWheelGUI operations that would lock up the system requiring a reset of of the ring (Galil and hardware firewall), GaliServer, and FilterWheelGUI. These FilterWheelGUI issues have not been addressed as far as I know.  Scott Swindell also noticed some of these issues and I actually worked with him a little as he made some small changes to improve the code.  This past year, Dan Avner was tasked to delve into the GalilServer & FilterWheelGUI code and see if there were issues that could help our reliability and recovery. He's mentioned there are quite a bit of potential issues within the code that could use some cleaning up and he believes are a major part of the problems. This is what makes the decision to continue to use the Galil or use another motion controller that much more difficult at this stage because these past problems and how much we don't know for sure is what seems to be driving things. We still need to get through regular operation of the 90Prime until we do the upgrade, which means it would be proper to make the necessary improvements in the GalilServer & FilterWheelGUI code in addition to many of the improvements I've mentioned in my writeup on a different thread to better serve our observers and mtnops folks.
 
3. Although the 61" Mont4K Galil Motion control system doesn't have some of the same conditions as the 90Prime, perhaps, we do not have the same problems there. We do have a GalilServer and FilterWheelGUI, but the GUI is less complex and seems to behave properly where one can't do things that causes a problem very easily. 

4. Although our network has been set up a certain way and seems to dictate that we use motion control products not as the manufacturer or any manufacturer or applications specialists recommends for that matter, we do have all kinds of options that are standard in the industry. Galil has provided a GalilServer like solution, GCAPS, and it's similar to how we plan to have our TCS talk to our axis drives on the telescopes. Our TCS single board computer is in between our network and our drives.  They are connected via an special industrial network, called EtherCat, which is an ethernet based fieldbus. The difference here is that a regular ethernet network is non-determinant so real-time communications is not possible, whereas EtherCat is set up for real-time operation. It uses a CANopen protocol that's been around for a long time, but required a special CANopen card in a computer or other hardware interface. Ethercat uses a standard network adaptor available in any computer.

5. We do have another method of communicating with the Galil via the serial RS-232 port and both Jeff Rill and myself have used this in earlier years to gain access to the Galil for configuration and monitoring reasons. It's a much slower comm at ~115K baud, but it's perfectly suitable for use by the software guys if they aren't using anything that requires higher bandwidth. Simply have the GalilServer talk to a Ethernet to RS-232 converter and the galil is on the network without any issues like before.  I have one and we've used in in the early years.

6. Something that is worth mentioning here as it addresses industry standards and the current state of affairs' in the cyber community. The teenage and simply malicious hackers have latched onto breaking into automated/robotic systems.  There has been a huge uptick on this sort of activity, specifically. Whether our Galil Motion controller is simply controlling a few actuators and wheels or we are controlling something that could hurt someone if the control got into the wrong hands, I believe we should try to adhere to certain industrial standards and practices when we can and even when we haven't in the past.

CONCLUSION:
1. Be nice to clean things up on the existing system, both for the sake of our customers throughout this next year as well as for our instrument people who have to tangle with things for sometimes 45 minutes or so due to problems after an instrument change.  Same thing goes for our operators in the middle of the night. This is a engineering issue and our observers and consequently our fu=first line defense folks, MtnOps, should not have to deal with situations where we know there are mechanical and software irregularities and we don't fix them.

2. I would like to continue with the mechanical improvements I've outlined in a separate report.  I believe both the known and unknown mechanical and software issues are essential while we continue to operate as well as look into the future.

4.  All the existing code, whether it be the GalilCode, GalilServer, or FilterWheelGUI, they have to be looked at because that's where the specifications are for anything new. I do not believe there is any documentation of the specifics of the software design and how it both operates, what it doesn't allow, how it handles this condition or that condition. It would seem the existing system is the only only real documentation we have to ensure certain aspects of the system aren't left out. And because of this, it would seem that much more plausible to evaluate issues that are found and how best to correct these issues as we still continue to operate. 

5.  I have not heard of any additional specifications for the 90Prime from a science point of view and every discussion seems to revolve around certain issues, both existing and nonexhibiting.  Although I have researched other motion control systems, such as Copley, Parker, ACS Motion Control, Yamaha, IMS, Delta Tau and others, in both coordinated and non-coordinated systems, I believe the Galil Motion Controller as we've been using is the best solution for time, budget, reliability, and robustness. Galil Motion has also been evolving these last 20 years as do all other motion control companies. I believe it's not good to place these types of motion control devises on standard networks due to safety. We may be able to continue with our existing hardware system, providing we shake out the known mechanical & software interaction issues. On the other side, it would be nice to install some components that aren't already 20 years old.

**Comment by grstafford** [comment]
**Been working on this for a while and talking with various manufacturers and vendors: Received their help in putting this together. There are many more solutions out there**

**Fully Coordinated Motion Controllers**
**1. Parker ACR7000**  (4 axis of coordinated motion): https://www.parkermotion.com/products/Controllers__7329__30_32_80_567_29.html
a. Servo and Stepper options
b. Uses Ethernet TCP/IP communication to PC.

**2. Parker ACR9000** (8 axis of coordinated motion): https://www.parkermotion.com/products/Controllers__6934__30_32_80_567_29.html
a. Parker really only has servo drives available to act as a slave for this, but a third party step drive (Copley) would work well as a slave.
b. Ethernet TCP/IP communications to PC.
c. Uses either +/- 10VDC analog command signals or Ethernet Powerlink to communicate with drives

**3. ACS motion control** (up to 64 axis coordinated motion): https://acsmotioncontrol.com/
a. Multiple different form factor options for both controllers and drives depending on application
b. Most drives can handle both servo and stepper interchangeably
c. Ethernet TCP/IP or serial communications to host PC
d. EtherCAT communications between controller and drive
e. Most powerful solution, has .NET, COM, and C libraries and a Labview interface
f. NanoPWM is great for high precision applications

**4. Yamaha** (up to 16 axis coordinated motion): https://global.yamaha-motor.com/business/robot/lineup/controller/rcx340/
a. Pretty much every field bus communication option
b. Ethernet TCP/IP and serial communications to host PC
c. Controller can natively handle SCARA or cartesian systems interchangeably

**Non-Coordinated Motion**
**1. Copley Motion** drives (single, dual, and 4 axis units):  https://www.copleycontrols.com/en/
a. Not true coordinated motion between drives if you are using the Copley built in controller
b. Serial communication option available, CanOpen option available
c. EtherCAT option would require a 3rd party EtherCAT master controller.

**2. IMS (Intelligent Motion Systems)** 
a. Integrated step motors for distributed control of single axis motors  https://motion.schneider-electric.com/

**Comment by dsand** [comment]
Thanks @grstafford.  From your standpoint, do any of these systems have any pros/cons with respect to the galil system?

**Comment by grstafford** [comment]
I would say they all have equal pros and cons depending on who you ask. Engineers get used to using certain hardware and that allows them to make better use of them to get the job done. The basics are pretty much universal. These days there are so many options available in some form or another. I do not have specific experience using the Parker multi-axis units, but I do for their single drives. I hear they are great. I have used IMS smart motors and discrete drives with serial interfaces and the ability to drop a program into them. They are great too. Delta Tau, Yamaha, and others will do the job quite nicely as they have a well-developed product line and some of our telescope folks could recommend them. I would recommend seeking additional help from others who have actually used other motion control systems, such as Tim Pickering, Ken Duffek, John Ford, Jeff Rill, Bill Siske and others.
