### ISSUE TITLE
FITS Header Keyword suggestions

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#36]
This will be a good place (or a google doc link off of here) to put in fits header keyword suggestions for 90Prime.

**Comment by griffin-h** [comment]
From the November engineering run log:
1. Numbers should be stored as numbers (not as strings)
2. Instead of  `FOCUSVAL= '*0.527*0.566*0.527' / Focus` Can we have
```
LVDTA = 0.527
LVDTB =0.566
LVDTC=0.527
```
3. For focus frames we should list list initial LVDT values, step size, and number of steps
4. Do not put `/` in header comments.  It terminates the comment.  See, e.g.:
```
GAIN1  = '1.5   '      / Conversion gain (e-
```

**Comment by mplesser** [comment]
All exposure should now have the LVDTA, LVDTB, LVDTC keywords (type float) in addition to the existing FOCUSVAL string keyword (which include the *).

A focus image should now also have FOCSTART (type string with the *), FOCSTEP (type float), FOCSHIFT (type int).

The slashes come from user defined templates, these all have to be manually edited.

**Comment by dsand** [comment]
We are going to test out the new guider keywords during the Feb 2022 engineering run.

**Comment by dsand** [comment]
Progress from the Feb 2022 run.  

1. Edit to CRVAL1 and CRVAL2 header keywords based on a bug Mike found.
2. The LVDTA, B, C keywords look good and seem to be reporting correctly, and are in sync with the FOCUSVAL keyword.
3. The FOCSTART, FOCSTEP, FOCSHIFT and FOCSTEPS all report in focus image, and the numbers seem correct.  There are still some issues with the int/float/string typing of these values.

Good progress!
