### ISSUE TITLE
Dan's GUI does not run on updated bart OS

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#38]
Here is Dan's reply on slack:

> Hmmmm so the new GUI requires a conda env that Phil builds for his python driver stuff. That probably broke with the new OS install.

assigning to @pndaly.

**Comment by pndaly** [comment]
Logging in as mtnops@bart:

% python3
Python 3.5.2 (default, Jan 26 2021, 13:30:48)
>>> 

% conda activate
% python3
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
>>>

So, the conda environment does give you v3.8 which is better because I use 'f-strings' in my code which were introduced in v3.6.

However, you *don't need* v3.8 to run the (indi) driver in normal operations as it just loads all the compiled C code (without any Python interfaces).

**Comment by davner** [comment]
I went on Bart this morning and started the service for the GUI. It is disabled and does not auto start.

`sudo systemctl start mtnops.pyindi.service`

If you navigate to `10.30.1.2:5905/ninety-prime` I see the GUI partially built. This requires the indiserver to be started for the entire GUI to appear. 

I don't think anything is wrong...

**Comment by pndaly** [comment]
OK, just did a quick test: started the bokGalilIndiDriver and then Dan's GUI. GUI gets populated and I think the *red* banners are because the shared memory segments are simulated (since the hardware is turned off). I'll try to attach the screenshot:
![bokGalilIndiGUI](https://user-images.githubusercontent.com/10948246/148434470-1f9d6da5-7a18-45cd-9264-1e3839d3db08.png)
