### ISSUE TITLE
Simplify startup procedure for 90PrimeGUI and website

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#53]
The current startup procedure requires a mtnops password, and the running of some scripts.  The plan is to simplify this and make it so that someone like Joe can simply start up the gui for a 90Prime run.  Dave does not understand the details, and will rely on @pndaly and @cjastro to bring this home!

**Comment by pndaly** [comment]
The new computer rack has been installed and the bokGalil, bok-90prime-gui and dataserver github repositories installed and the code built. All of this has been effected under the primefocus account on bonsai and banzai. On the night of 15 September this was tested and first light was achieved with the 6k engineering detector. No privilege is required to run this code. A SOP-document is in prep detailing the new startup procedures. So, this issue is now complete.
