### ISSUE TITLE
Prep for June 2022 run and use of new dewar and 6K chip

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#54]
I will start this thread off with a copy of Joe's email to @mplesser from May 2, 2022.

> I wanted to start a list of items to think about for the run in June. I know you are on vacation now, but thought we could start talking about some of these things when you get back.:
> 
> How does the new camera power supply mount? Is it the same size as the old one? Does it need to be mounted to g-10? The old camera power supply has a grounding wire running from it to an isolated outlet on the north plate. Does the new one need this?
> Will there be a new camera cable from the power supply to the camera? If so, do you need measurements of the old one? I cannot remember if we measured that previously.
> The new camera controller uses Ethernet cable instead of fiber from what I understand. Do you need an estimated length for this cable to go between the new controller and the new Ethernet switch on the north plate? Does this need to be a special cable or just a basic Ethernet cable?
> Will the new camera be using the same shutter connector and cable that is already on the scope that the old camera uses?
> Will we need to pump and chill the camera on the mountain for the run in June?
> Will we be using BokCCD2 to run the new camera in June?
> Will new AzCam software be added to run the camera or does it use the current software?
> I'll send more questions as I think of them. I have missed quite a few of the 90Prime meetings so I'm sorry if you have already answered these questions elsewhere.

**Comment by mplesser** [comment]
How does the new camera power supply mount? Is it the same size as the old one? Does it need to be mounted to g-10? The old camera power supply has a grounding wire running from it to an isolated outlet on the north plate. Does the new one need this?
Will there be a new camera cable from the power supply to the camera? If so, do you need measurements of the old one? I cannot remember if we measured that previously.

**--> there is no separate power supply for the new controller.  It has a 110V power requirement right at the controller, so this is new. We need to be able to cycle this power remotely so that needs to be thought out.**

The new camera controller uses Ethernet cable instead of fiber from what I understand. Do you need an estimated length for this cable to go between the new controller and the new Ethernet switch on the north plate? Does this need to be a special cable or just a basic Ethernet cable?

**--> we should have a CAT6 ethernet cable from the controller to where ever it plugs into the network (North plate)? I can order it if someone tells me how long it should be, or we may have one in the lab.**

Will the new camera be using the same shutter connector and cable that is already on the scope that the old camera uses?

**--> No, the controller has a BNC shutter output connector (not the same as the ARC controller). I do not remember what Bonn shutter needs but I think it is BNC also.  So we need a standard BNC-BNC cable of the right length. I may have one in the lab if someone can send the length needed.**

Will we need to pump and chill the camera on the mountain for the run in June?
**--> Unknown**

Will we be using BokCCD2 to run the new camera in June?

**--> Yes**

Will new AzCam software be added to run the camera or does it use the current software?

**--> New software but it looks the similar**

**Comment by dsand** [comment]
From Gary R. on May 25:

> I went up to the 90" on Monday for an instrument change. Joe asked me to make the following measurements for cable lengths for the new 90prime camera but did not tell me who to send the info to. I have not seen the new 90prime dewar, so I measured to the point on the old camera where we plug in to the connectors on the camera controller. For the old 90prime camera I measured from the base of the camera where it is bolted to 90prime to the connectors on the CCD controller, allowing extra cable length to wrap around to the connectors on top of the controller with no stress on the cables (2.5').

>Power cord, from the 2 outlet box (clean power) on the upper ring plate to the old 90prime camera controller connectors, 11'.
Bonn shutter driver to the old 90prime camera controller connectors, 10.5'.
New network switch to the old 90prime camera controller connectors, 11'.
You should add at least 6" to these measurements to make sure there is no stress on any of the connectors.

**Comment by dsand** [comment]
Will close this since June 2022 run did not happen.  Will open new issues if any of the above points come up again.
