### ISSUE TITLE
Office Prep for new 90Prime computers

### ISSUE THREAD

**Issue by dsand** [so-90prime/90prime#58]
Two things need to be done before we can use the 2nd floor office at the 90-in for the new 90Prime computers.  
1. Fiber needs to be run down from dome.
2. Electrical capacity.  There is at least one 20amp circuit in the office that may be shared with adjacent rooms.  Is there a second?

We also should pay attention to the temperature in the office, as there is heating but no AC.

Will keep this open until new 90Prime computers are snug in the office, or another decision is made.

**Comment by pndaly** [comment]
We know there are 3 x 20A circuits in the room. Fiber has been run down and connected to the newly installed computer rack. Everything is working: rack is much quieter than anticipated and heat output is low. We have the rack in the middle of the floor with the back off. As it is now, we can access all 4 sides easily so. The back has to remain off, though, because of the 4" bend radius on the fiber. That said, there is enough room for a desk/chair in there as well.

Issue closed.
